#[derive(Debug)]
#[derive(Queryable)]
pub struct ZoneTable {
    efId: i32,
    zoneID: i32,
    locStatus: i32,
    zoneName: String,
    scriptID: i32,
    ghostdistance_min: f64,
    ghostdistance: f64,
    population_soft_cap: i32,
    population_hard_cap: i32,
    DisplayDescription: String,
    mapFolder: String,
    smashableMinDistance: f64,
    smashableMaxDistance: f64,
    mixerProgram: String,
    clientPhysicsFramerate: String,
    serverPhysicsFramerate: String,
    zoneControlTemplate: i32,
    widthInChunks: i32,
    heightInChunks: i32,
    petsAllowed: i32,
    localize: i32,
    fZoneWeight: f64,
    thumbnail: String,
    PlayerLoseCoinsOnDeath: i32,
    disableSaveLoc: i32,
    teamRadius: f64,
    gate_version: String,
    mountsAllowed: i32,
}